"""Added new report Column 'is_rerun_report'

Revision ID: d2e3172edcd9
Revises: 
Create Date: 2020-03-10 11:15:16.745933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e3172edcd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('is_return_report', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'is_return_report')
    # ### end Alembic commands ###
